### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by SSSn0w** [SSSn0w/SVNE#1]
# To-Do List
==============================================
- [ ] Transitions
- [ ] Animations

==============================================
- [ ] Sprite Stage Positions
- [x] Sprite Collection (Drawable List)

==============================================
- [x] Texture Button
- [x] Text Button
- [x] Slider
- [ ] Check box
- [ ] Text Input
- [ ] Menus and Options

==============================================
- [x] Event Timeline
- [x] Scenes (in a separate timeline)
- [x] Event Triggers
- [x] Scene/Menu Change Event Triggers
- [x] Decision/Option Event
- [x] Music/Sound Event
- [ ] Video Player

==============================================
- [x] Loading and Saving the Game
- [x] Load Images File (to load assets for each component)
- [ ] Visual Novel Scripting Language + Parser

==============================================
- [ ] Cross Platform Compatibility (OpenTK + Dotnet Core)

==============================================
